### ISSUE TITLE
how can I  create sdf voxel grids for scannet data

### ISSUE THREAD

**Issue by ShenTingD** [skanti/Scan2CAD#19]
How can I get the .vox data for scannet scene? Do you have the code or the data?

**Comment by DerT0bi** [comment]
Hi, I have the same problem. Did you find a solution to this?

**Comment by ShenTingD** [comment]
> Hi, I have the same problem. Did you find a solution to this?

sorry,I have not solved it yet, the download link seems useless.

**Comment by YuePanEdward** [comment]
Same question

**Comment by saladcat** [comment]
Same question

**Comment by NiuCY** [comment]
You can refer to this link, but I don't know how should I set the parameters.
https://github.com/skanti/generate-watertight-meshes-and-sdf-grids

**Comment by IAMShashankk** [comment]
@ShenTingD Were you able to convert the ScanNet data? Could you please share your findings?

**Comment by zhixuanbamn** [comment]
@skanti @NiuCY  I also have the same issue, I try multiple ways but still can't get the voxelised sdf voxel grids from scannet data. Please let me know if you have any advice.
