### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by Co1lin** [skanti/Scan2CAD#21]
Hi! I've filled the form for requesting dataset at least one week ago, but I received nothing in my mailbox. Maybe there's something wrong with the google form. Could you please send me the dataset? I really need this for research purpose. Thank you very much!

**Comment by yang-Michael** [comment]
Hello, had you already received the download link or any script? I had filled the form for requesting dataset, but no response. Could you share me the download link? Just for research purpose. Thx!
