### ISSUE TITLE
scannet dataset

### ISSUE THREAD

**Issue by jade2014** [skanti/Scan2CAD#3]
hi
I use volumetric fusion get the TSDF result of ScanNet(0470_00), the voxel resolution is 3cm and truncation is 15cm(grid num(116,95,46)). The result is very worse, can you give some more detail about obtain TSDF of ScanNet datasets.
<img width="518" alt="屏幕快照 2019-03-14 17 38 50" src="https://user-images.githubusercontent.com/8266482/54346758-9a4ce680-4680-11e9-8a37-a48e7144cdb5.png">

**Comment by skanti** [comment]
Hi, currently i'm a little busy with a conference deadline. I'll provide the code for it in 2-3 weeks. Thanks

**Comment by EDGSCOUT** [comment]
how to get the dataset? i have written the registration,and after how long time can i get the dataset.

**Comment by flamehaze1115** [comment]
Hi, would you please talk more about how to process the scannet data and get the .vox file? Thanks

**Comment by yuchenrao** [comment]
Hi, have you finished the corresponding code? Thanks a lot! @skanti

**Comment by yang-Michael** [comment]
Hello, had you already received the download link or any script? I had filled the form for requesting dataset, but no response. Could you share me the download link? Just for research purpose. Thx!
