### ISSUE TITLE
List out of range in Annotation2Mesh.py, line 115

### ISSUE THREAD

**Issue by LR32768** [skanti/Scan2CAD#5]
The dataset faces mainly consist of 3 vertices hence the array f is always a 3-tuple array, however in line 115 of Annotation2Mesh.py it just call f[3], which makes the program crash. 
Did you notice this apparent error or is there something I missed to cause such problem?

**Comment by skanti** [comment]
Hi, thanks for the heads up. Does it actually crash also with the sample meshes for you? For me it works without crashing, but I agree 3 should be out of range

**Comment by LR32768** [comment]
> Hi, thanks for the heads up. Does it actually crash also with the sample meshes for you? For me it works without crashing, but I agree 3 should be out of range

I am not sure. I download the full_annotations.json as you instructed and put it at the directory ./Rountines/Script, then run the Annotation2Mesh.py and this is what I got, is there anything I miss?

**Comment by LR32768** [comment]
> Hi, thanks for the heads up. Does it actually crash also with the sample meshes for you? For me it works without crashing, but I agree 3 should be out of range

Hence I believe it is the sample meshes

**Comment by LR32768** [comment]
Also, I see there is a demo for oriented bounding box, but I didn't find where is the visualization for it. Could you please inform the place of that part of code to visualize the bounding box for each CAD model in aligned scene?

**Comment by EDGSCOUT** [comment]
The dataset faces mainly consist of 3 vertices hence the array f is always a 3-tuple array, however in line 115 of Annotation2Mesh.py it just call f[3], which makes the program crash.
is this problem solved?

**Comment by EDGSCOUT** [comment]
> Also, I see there is a demo for oriented bounding box, but I didn't find where is the visualization for it. Could you please inform the place of that part of code to visualize the bounding box for each CAD model in aligned scene?



> The dataset faces mainly consist of 3 vertices hence the array f is always a 3-tuple array, however in line 115 of Annotation2Mesh.py it just call f[3], which makes the program crash.
> Did you notice this apparent error or is there something I missed to cause such problem?

are you solve this problem now?

**Comment by LR32768** [comment]
> > Also, I see there is a demo for oriented bounding box, but I didn't find where is the visualization for it. Could you please inform the place of that part of code to visualize the bounding box for each CAD model in aligned scene?
> 
> > The dataset faces mainly consist of 3 vertices hence the array f is always a 3-tuple array, however in line 115 of Annotation2Mesh.py it just call f[3], which makes the program crash.
> > Did you notice this apparent error or is there something I missed to cause such problem?
> 
> are you solve this problem now?

no, and haven't find a way to bypass it either

**Comment by skanti** [comment]
fixed this bug with the latest commit :)
