### ISSUE TITLE
Where to find the evaluate script

### ISSUE THREAD

**Issue by DevinHA** [skanti/Scan2CAD#6]
Hello, nice work! But I'd like to know where to find the evaluation script that do evaluate on the retrieval results. Follow http://kaldir.vc.in.tum.de/scan2cad_benchmark/documentation, I can't find the script in this repo. I can only find the evaluation on the 'heatmap' and 'ismatch'. Maybe I just missed that?

**Comment by skanti** [comment]
Hi,
thanks for the note, i'll upload it asap in the github repo :)

**Comment by jingnanshi** [comment]
Hi, has the evaluation script been uploaded? Thanks

**Comment by moshanATucsd** [comment]
https://github.com/skanti/Scan2CAD/blob/master/Routines/Script/EvaluateBenchmark.py
